### ISSUE TITLE
[repository] retorno do insert

### ISSUE THREAD

**Issue by yaansz** [FerroEduardo/SAMU-Sistema-de-Auxilio-a-Matricula-Universitaria#14]
o retorno das funções insert deve ser True/False ou void? Já que o objeto é um ponteiro então ele sempre é atualizado

**Comment by yaansz** [comment]
Ainda precisamos unificar o padrão de retornos dos inserts/finds/etc

**Comment by FerroEduardo** [comment]
Temos que trocar os Optional para as Exception para poder ter mais flexibilidade
