### ISSUE TITLE
problemas com a relação entre student e lecture

### ISSUE THREAD

**Issue by yaansz** [FerroEduardo/SAMU-Sistema-de-Auxilio-a-Matricula-Universitaria#17]
um faz referencia ao outro, em algum momento do carregamento isso poderia causar um loop, provocando um stackoverflow ou algo assim

**Comment by yaansz** [comment]
Talvez a disciplina não deva conhecer List<Students> ou instanciar uma lista de users já que não armazena esse tipo de informação (Lectures)

**Comment by FerroEduardo** [comment]
Que tal manter tudo em String e só obter os objetos do BD quando necessário?
Imagino que isso resolva o problema parcialmente.

**Comment by yaansz** [comment]
```java
    private String name;
    private String description;
    private String code;
    private ArrayList<String> prerequisites;
```
A solução que foi implementada no Subject deve ser a melhor opção mesmo

**Comment by yaansz** [comment]
Tava pensando em talvez os repositories guardarem todas as referencias para todos os objetos carregados e a partir disso poder verificar se já está na memória tal objeto. Uma boa saída

```java
public class StudentRepository {

   List<Students> loadedStudents;

  public Student search(String code/id/name) throws UserNotFound
}
```
