### ISSUE TITLE
[DATABASE] Tabelas necessárias

### ISSUE THREAD

**Issue by yaansz** [FerroEduardo/SAMU-Sistema-de-Auxilio-a-Matricula-Universitaria#9]
Por enquanto temos duas tabelas (Student, Subjects) mas acho que vamos precisar de uma própria para o login para descobrir se o usuário é um coordenador ou um aluno (se der tempo um professor).

**Comment by yaansz** [comment]
O ideal é começarmos a modelar o sistema nesse final de semana

**Comment by FerroEduardo** [comment]
Faltam as disciplinas cursadas pelo aluno

**Comment by FerroEduardo** [comment]
Falta o estado atual da disciplina, se aberta, fechada,...

**Comment by yaansz** [comment]
adicionei aos singletons pq a base da implementação ta feita, mas creio ser necessário mais tabelas se houver tempo (period, course and curriculum)!
